version: "2"

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw

  ##################################################
  #                   Hosts                        #
  ##################################################

  portfolio.everydayweekend.net:
    image: florianporada/portfolio:latest
    environment:
      - VIRTUAL_HOST=portfolio.everydayweekend.net

  everydayweekend.net:
    image: florianporada/everydayweekend.net:latest
    environment:
      - VIRTUAL_HOST=everydayweekend.net,www.everydayweekend.net

  florianporada.com:
    image: florianporada/placeholder:latest
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=florianporada.com,www.florianporada.com
      - LETSENCRYPT_HOST=*.florianporada.com

  constantlyunderdressed.party:
    image: florianporada/constantlyunderdressed.party:latest
    environment:
      - VIRTUAL_HOST=constantlyunderdressed.party,www.constantlyunderdressed.party

  werputzt.fun:
    image: florianporada/werputzt.fun:latest
    environment:
      - VIRTUAL_HOST=werputzt.fun,www.werputzt.fun

  kitt.cool:
    image: florianporada/kitt.cool:latest
    environment:
      - VIRTUAL_HOST=kitt.cool,www.kitt.cool
