version: "2"

services:
  nginx-proxy:
    image: nginx-proxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  portfolio.everydayweekend.net:
    image: florianporada/portfolio:latest
    environment:
      - VIRTUAL_HOST=portfolio.everydayweekend.net

  everydayweekend.net:
    image: florianporada/everydayweekend.net:latest
    environment:
      - VIRTUAL_HOST=everydayweekend.net,www.everydayweekend.net

  constantlyunderdressed.party:
    image: florianporada/constantlyunderdressed.party:latest
    environment:
      - VIRTUAL_HOST=constantlyunderdressed.party,www.constantlyunderdressed.party

  # werputzt.fun:
  #   image: florianporada/werputzt.fun:latest
  #   environment:
  #     - VIRTUAL_HOST=werputzt.fun,www.werputzt.fun

  kitt.cool:
    image: florianporada/kitt.cool:latest
    environment:
      - VIRTUAL_HOST=kitt.cool,www.kitt.cool
