version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

  everydayweekend.net:
    image: crccheck/hello-world:latest
    environment:
      - VIRTUAL_HOST=everydayweekend.net
      - VIRTUAL_PORT=8000

  constantlyunderdressed.party:
    image: karthequian/helloworld:latest
    environment:
      - VIRTUAL_HOST=constantlyunderdressed.party
